### ISSUE TITLE
Implement due dates on proposal review/answering

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-reporting-proposals#1]
This job has been done as feature for Decidim. Product does not want this so we will be moving it at this plugin as a feature.

Original PR:
https://github.com/openpoke/decidim/pull/9

**Tasks:**

- [x] Move new styles to this plugin
- [x] Override by including a new concern adding the new introduced methods for `Admin::ProposalHelper`
- [x] Move locales to this plugin
- [x] override admin/_proposal-tr.html.erb (include in the lib/override_specs.rb test)
- [x] Move specs to this repository
