### ISSUE TITLE
Buttons to link additional "reporting proposals" component in the same participatory space

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-reporting-proposals#14]
**Original Request**

As a user, I would like an additional button next to "add a proposal" so that I can quickly switch from idea to damage (and vice versa).
(--> One Button for "reporting a damage" and one for "reporting an idea", that links to the second tab).
Example link settings: https://letterbox.dev.pokecode.net/admin/participatory_processes/digital-letterbox/components/2/edit

**Implementation**

Instead of limiting the button to a concept of damage or idea, we will create in the component settings a new input with the name of the button and a URL. This way the admin is free to use this extra button to whatever they want

**Implementation screnshots**

![photo_2022-10-05_13-42-09](https://user-images.githubusercontent.com/1401520/194052684-9e74664b-0ed0-4264-995c-fdc3d5c73a7c.jpg)

![image](https://user-images.githubusercontent.com/1401520/194070147-60d96974-9bf7-4429-bdd9-8601dbb7b695.png)

**Tasks**

In a given participatory space, many components of the type "Reporting proposals" can be added

- [x] Add an option in the component settings for adding a new button next to "new proposal". Text and link should be configurable.
- [x] Display the button in the index public view if configured
- [ ] Specs for it
