### ISSUE TITLE
Time completion: time elapsed to answer a proposal

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-reporting-proposals#16]
**Original request**

As a process-admin, I would like to see the time of completion in the Excel export (as soon as the status changes to completed/accepted).

**Context**

Proposals have a answer `state` and a  `answered_at` time field. In the admin it is possible to see the state but not values on how long it took to answer the proposals (and giving a final state).

![imatge](https://user-images.githubusercontent.com/40388743/194073662-ed08a000-2da4-4ba7-8dd8-252698606c07.png)

**Tasks**

- [x] Add the time elapsed information in a new method in the proposals model
- [x] Use this info for answered proposals, show it in the admin?
- [x] Add this info in a column in the generated CSV/Excel when exporting proposals
- [x] Tests
