### ISSUE TITLE
Hide proposals without reporting

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-reporting-proposals#2]
**Original requirement:**

As a process-admin, I would like to be able to hide proposals directly via the backend without the need of first report the proposal via frontend.

**Context**

In Decidim a proposal needs to be reported before it can be hidden (see https://github.com/openpoke/decidim/issues/22).

> Allowing admins to hide content without reporting it first does not comply with the social contract, so this is going to be done in this module.

**Tasks**
- [x] Add a configuration option for this module `Decidim::ReportingProposals.allow_admins_to_hide_proposals`
- [x] If configuration active, override the view when managing a proposal in the admin, add a button saying "hide this proposal" (*the flag in the mockup*). Show the same modal window that appears in the frontend side when you press the "report" flag button.

*Frontend current flag report button:*
![image](https://user-images.githubusercontent.com/1401520/191001119-131ec6fd-1447-4a7f-970e-1ab542ff77ac.png)

*Mockup:*
![image](https://user-images.githubusercontent.com/1401520/190999647-6bfa6be1-a6e2-425f-83f6-7f0c2124beb0.png)

- [x] Add a controller in this module that handles the action of creating a report and hiding the content (use existing commands `CreateReport` and/or `HideResource` from decidim).
- [x] Add a entry to the spec/lib/overrides_spec.rb to keep track of the overriden view file.
- [x] Prevent to generate notifications/emails to other admins if hidden by the admin. Affected user should still receive their notification.
- [x] When hiding, use the same modal with the options on why are you hidding that (can be used as confirmation dialog)
- [x] Add behaviour specs for this

**Dev notes:**

- Create a new branch from `main` in this repository and PR against it.
- How to override a class (ie: a controller), using Concerns that are initialized  in https://github.com/openpoke/decidim-module-reporting-proposals/blob/main/lib/decidim/reporting_proposals/engine.rb (ie: ` Decidim::Proposals::ProposalsController.include(Decidim::ReportingProposals::ProposalsControllerOverride)`)
- Views can just be overridden by replicating the same structure of the original in the module.
